services:
  backend:
    build: ./abscribe_backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=mongodb
      - FLASK_ENV=production # Set Flask environment to production
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./abscribe_frontend
      args:
        REACT_APP_VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        REACT_APP_GPT_URL: ${GPT_URL}
    ports:
      - "80:80" # NGINX default port
    environment:
      # - VITE_BACKEND_URL=http://145.38.194.189/api/
      - VITE_BACKEND_URL=http://backend/api/
      - GPT_URL=http://localhost:11435/
    depends_on:
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
