apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shreyansure8/cillm:backend-latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_HOST
              value: "mongodb"
            - name: FLASK_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
